### ISSUE TITLE
'tokio-runtime-worker' panicked at 'not zero terminated'

### ISSUE THREAD

**Issue by ivanmilov** [phiresky/timetrackrs#12]
Hi, I use `Linux  5.4.0-94-generic #106-Ubuntu  x86_64 GNU/Linux`

after building I run `RUST_BACKTRACE=1 ~/.cargo/bin/timetrackrs` and have this output:
```
2022-01-20T18:34:44.713231Z  INFO timetrackrs::db: Running 6 migrations 
Configuration: TimetrackrsConfig {
    capturers: [
        CaptureConfig {
            interval: 30s,
            args: NativeDefault(
                NativeDefaultArgs,
            ),
        },
    ],
    server: Some(
        ServerConfig {
            listen: [
                "127.0.0.1:52714",
            ],
        },
    ),
}
starting server at http://127.0.0.1:52714
new id generated: c7kqmh04ooc839fc5gc0
2022-01-20T18:34:44.808347Z  INFO timetrackrs::capture: sleeping 30s
thread 'tokio-runtime-worker' panicked at 'not zero terminated', src/capture/linux/types.rs:121:9
stack backtrace:
reporting root done
   0: std::panicking::begin_panic
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:604:12
   1: timetrackrs::capture::linux::types::split_zero
             at ./src/capture/linux/types.rs:121:9
   2: <timetrackrs::capture::linux::x11::X11Capturer<C> as timetrackrs::capture::Capturer>::capture
             at ./src/capture/linux/x11.rs:123:29
   3: timetrackrs::capture::capture_loop::{{closure}}
             at ./src/capture/mod.rs:67:20
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/future/mod.rs:84:19
   5: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:161:17
   6: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/loom/std/unsafe_cell.rs:14:9
   7: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:151:13
   8: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:461:19
   9: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/panic/unwind_safe.rs:271:9
  10: std::panicking::try::do_call
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:485:40
  11: std::panicking::try
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:449:19
  12: std::panic::catch_unwind
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panic.rs:136:14
  13: tokio::runtime::task::harness::poll_future
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:449:18
  14: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:98:27
  15: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:53:15
  16: tokio::runtime::task::raw::RawTask::poll
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:70:18
  17: tokio::runtime::task::LocalNotified<S>::run
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/mod.rs:343:9
  18: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:420:13
  19: tokio::coop::with_budget::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
  20: std::thread::local::LocalKey<T>::try_with
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/thread/local.rs:413:16
  21: std::thread::local::LocalKey<T>::with
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/thread/local.rs:389:9
  22: tokio::coop::with_budget
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  23: tokio::coop::budget
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  24: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:419:9
  25: tokio::runtime::thread_pool::worker::Context::run
  26: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:371:17
  27: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/macros/scoped_tls.rs:61:9
  28: tokio::runtime::thread_pool::worker::run
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:368:5
  29: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/worker.rs:347:45
  30: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/task.rs:42:21
  31: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:161:17
  32: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/loom/std/unsafe_cell.rs:14:9
  33: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/core.rs:151:13
  34: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:461:19
  35: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/panic/unwind_safe.rs:271:9
  36: std::panicking::try::do_call
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:485:40
  37: std::panicking::try
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:449:19
  38: std::panic::catch_unwind
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panic.rs:136:14
  39: tokio::runtime::task::harness::poll_future
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:449:18
  40: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:98:27
  41: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/harness.rs:53:15
  42: tokio::runtime::task::raw::RawTask::poll
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/raw.rs:70:18
  43: tokio::runtime::task::UnownedTask<S>::run
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/task/mod.rs:379:9
  44: tokio::runtime::blocking::pool::Inner::run
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/pool.rs:264:17
  45: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/blocking/pool.rs:244:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Error: panic

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.52/src/error.rs:530:25
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/result.rs:2052:27
   2: timetrackrs::main::{{closure}}
             at ./src/bin/timetrackrs.rs:86:9
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/future/mod.rs:84:19
   4: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/park/thread.rs:263:54
   5: tokio::coop::with_budget::{{closure}}
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
   6: std::thread::local::LocalKey<T>::try_with
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/thread/local.rs:413:16
   7: std::thread::local::LocalKey<T>::with
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/thread/local.rs:389:9
   8: tokio::coop::with_budget
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
   9: tokio::coop::budget
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  10: tokio::park::thread::CachedParkThread::block_on
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/park/thread.rs:263:31
  11: tokio::runtime::enter::Enter::block_on
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/enter.rs:151:13
  12: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/mod.rs:77:9
  13: tokio::runtime::Runtime::block_on
             at /home/i/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/mod.rs:463:43
  14: timetrackrs::main
             at ./src/bin/timetrackrs.rs:90:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/ops/function.rs:227:5
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/sys_common/backtrace.rs:123:18
  17: std::rt::lang_start::{{closure}}
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/rt.rs:145:18
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/core/src/ops/function.rs:259:13
  19: std::panicking::try::do_call
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:485:40
  20: std::panicking::try
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:449:19
  21: std::panic::catch_unwind
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panic.rs:136:14
  22: std::rt::lang_start_internal::{{closure}}
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/rt.rs:128:48
  23: std::panicking::try::do_call
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:485:40
  24: std::panicking::try
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panicking.rs:449:19
  25: std::panic::catch_unwind
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/panic.rs:136:14
  26: std::rt::lang_start_internal
             at /rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/rt.rs:128:20
  27: main
  28: __libc_start_main
  29: _start
```

**Comment by phiresky** [comment]
looks like the WM_CLASS of some window looks different than expected.. if you can identify from which window it comes that would be helpful (you can use `xprop |grep WM_CLASS` to find out the wm class of programs, should be two strings

**Comment by ivanmilov** [comment]
So far I "fixed" it commenting out the panic:
```rust
// "2\u{0}4\u{0}5\u{0}6\u{0}8\u{0}9\u{0}1\u{0}" to array of strings
pub fn split_zero(s: &str) -> Vec<String> {
    let mut vec: Vec<String> = s.split('\0').map(String::from).collect();
    // let last = vec.pop().unwrap();
    // if !last.is_empty() {
    //     panic!("not zero terminated");
    // }
    vec
}
```

**Comment by ivanmilov** [comment]
and yes:
```bash
❯ xprop | grep WM_CLASS                     
WM_CLASS(STRING) = "konsole", "konsole"
```

**Comment by phiresky** [comment]
that konsole string looks fine - it could be in another window. maybe you could add a log::warn!("unexpected class: {vec:#?}") in the `if !last.is_empty()`?

**Comment by ivanmilov** [comment]
Ok, I guess it happens because of my custom desktop names:
![image](https://user-images.githubusercontent.com/522518/150405354-7cca1a69-9fb7-4457-97b9-a241262f664f.png)

**Comment by phiresky** [comment]
uh, that's weird that those are in the window class though - can you say which window manager and status bar etc you are using?

**Comment by ivanmilov** [comment]
bspwm and polybar

**Comment by ivanmilov** [comment]
and I think it called from here: `let desktop_names = split_zero(&get_property_text(...`, so desktop names

**Comment by phiresky** [comment]
ah, i forgot that that function is also used there. I guess the panic should only apply to classes then, where it makes sense to strip out the last empty bit

**Comment by phiresky** [comment]
There seems to be an inconsistency in the way the string lists are created, bspwm not zero-terminating the list. I've added a check that only removes the last element if it is empty, this should fix it. Let me know if you still encounter this issue.
